appname = spp-app
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true

# Konfigurasi Database
mysqluser = "root"
mysqlpass = "password_kamu"
mysqlurls = "127.0.0.1"
mysqldb   = "nama_database_spp"